USE [master]
GO

/****** Object:  Database [Movie]    Script Date: 11-07-2023 12:53:19 ******/
CREATE DATABASE [Movie]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Movie', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Movie.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Movie_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Movie_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Movie].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Movie] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Movie] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Movie] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Movie] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Movie] SET ARITHABORT OFF 
GO

ALTER DATABASE [Movie] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Movie] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Movie] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Movie] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Movie] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Movie] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Movie] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Movie] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Movie] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Movie] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Movie] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Movie] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Movie] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Movie] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Movie] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Movie] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Movie] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Movie] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Movie] SET  MULTI_USER 
GO

ALTER DATABASE [Movie] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Movie] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Movie] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Movie] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Movie] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Movie] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Movie] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Movie] SET  READ_WRITE 
GO


